import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../../core/theme/app_theme.dart';
import '../../../../core/utils/extensions.dart';
import '../../domain/entities/account.dart';
import '../bloc/account_bloc.dart';

/// ═══════════════════════════════════════════════════════════════════════════
/// Account Create/Edit Screen - Form to create or edit account
/// ═══════════════════════════════════════════════════════════════════════════
class AccountCreateScreen extends StatefulWidget {
  final Account? account;
  
  const AccountCreateScreen({super.key, this.account});

  @override
  State<AccountCreateScreen> createState() => _AccountCreateScreenState();
}

class _AccountCreateScreenState extends State<AccountCreateScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _balanceController = TextEditingController();

  String _selectedType = 'bank';
  bool _isLoading = false;
  bool _isEditMode = false;

  // Account type options
  final List<Map<String, dynamic>> _accountTypes = [
    {'value': 'bank', 'label': 'Bank', 'icon': Icons.account_balance, 'enabled': true},
    {'value': 'cash', 'label': 'Cash', 'icon': Icons.money, 'enabled': true},
    {'value': 'ewallet', 'label': 'E-Wallet', 'icon': Icons.phone_android, 'enabled': true},
    {'value': 'debit', 'label': 'Wallet', 'icon': Icons.wallet, 'enabled': false}
  ];

  @override
  void initState() {
    super.initState();
    _isEditMode = widget.account != null;
    
    // Populate fields if editing
    if (widget.account != null) {
      _nameController.text = widget.account!.name;
      _balanceController.text = widget.account!.balance.toStringAsFixed(2);
      _selectedType = widget.account!.type;
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _balanceController.dispose();
    super.dispose();
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Actions
  // ─────────────────────────────────────────────────────────────────────────

  /// Handle create or update account
  Future<void> _handleSaveAccount() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final balance = double.tryParse(_balanceController.text) ?? 0.0;
      final now = DateTime.now();

      if (_isEditMode) {
        // Update existing account
        final updatedAccount = widget.account!.copyWith(
          name: _nameController.text.trim(),
          type: _selectedType,
          balance: balance,
          updatedAt: now,
        );

        print('📝 Updating account: ${updatedAccount.name} (${updatedAccount.type}) - Balance: ${updatedAccount.balance}');

        if (mounted) {
          context.read<AccountBloc>().add(UpdateAccountRequested(updatedAccount));
        }
      } else {
        // Create new account
        final account = Account(
          id: '', // Will be generated by database
          name: _nameController.text.trim(),
          type: _selectedType,
          openingBalance: balance,
          balance: balance,
          currency: 'THB', // App supports only Thai Baht
          createdAt: now,
          updatedAt: now,
        );

        print('📝 Creating account: ${account.name} (${account.type}) - Balance: ${account.balance} ${account.currency}');

        if (mounted) {
          context.read<AccountBloc>().add(CreateAccountRequested(account));
        }
      }
      
      // Wait for the bloc to process the event
      await Future.delayed(const Duration(milliseconds: 800));
      
      // Return success
      if (mounted) {
        print('✅ Account save completed, navigating back');
        Navigator.pop(context, true);
      }
    } catch (e) {
      if (mounted) {
        context.showSnackBar('Failed to save account: $e', isError: true);
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Build Methods
  // ─────────────────────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: context.colors.scaffoldBg,
      appBar: context.styles.appBar(title: _isEditMode ? 'Edit Account' : 'Create Account'),
      body: _buildBody(),
    );
  }

  /// Build body
  Widget _buildBody() {
    return Column(
      children: [
        Expanded(
          child: SingleChildScrollView(
            padding: const EdgeInsets.fromLTRB(20, 24, 20, 140),
            child: Form(
              key: _formKey,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Account name field
                  _buildSectionLabel('Account Name'),
                  const SizedBox(height: 8),
                  _buildNameField(),
                  const SizedBox(height: 24),

                  // Account type field
                  _buildSectionLabel('Account Type'),
                  const SizedBox(height: 12),
                  _buildTypeSelector(),
                  const SizedBox(height: 24),

                  // Current balance field
                  _buildSectionLabel('Current Balance'),
                  const SizedBox(height: 12),
                  _buildBalanceField(),
                  const SizedBox(height: 8),
                  Text(
                    'This reflects how much money is currently in this account.',
                    style: context.styles.caption,
                  ),
                ],
              ),
            ),
          ),
        ),
        _buildBottomActions(),
      ],
    );
  }

  Widget _buildSectionLabel(String label) {
    return Text(label, style: context.styles.label);
  }

  Widget _buildNameField() {
    return TextFormField(
      controller: _nameController,
      style: context.styles.inputText,
      decoration: context.styles.input(
        hint: 'e.g. Main Bank, Cash, Wallet',
      ),
      validator: (value) {
        if (value == null || value.trim().isEmpty) {
          return 'Please enter account name';
        }
        return null;
      },
    );
  }

  Widget _buildTypeSelector() {
    return GridView.count(
      crossAxisCount: 2,
      shrinkWrap: true,
      physics: const NeverScrollableScrollPhysics(),
      crossAxisSpacing: 12,
      mainAxisSpacing: 12,
      childAspectRatio: 2.5,
      padding: EdgeInsets.zero,
      children: _accountTypes.map((type) {
        final isSelected = _selectedType == type['value'];
        final isEnabled = type['enabled'] as bool;
        
        return InkWell(
          onTap: isEnabled ? () => setState(() => _selectedType = type['value']) : null,
          borderRadius: BorderRadius.circular(AppDimens.radiusSm),
          child: Opacity(
            opacity: isEnabled ? 1.0 : 0.5,
            child: Container(
              decoration: BoxDecoration(
                color: isSelected ? context.colors.accentLight : context.colors.cardBg,
                borderRadius: BorderRadius.circular(AppDimens.radiusSm),
                border: Border.all(
                  color: isSelected ? context.colors.accent : context.colors.border,
                  width: isSelected ? 1.5 : 0.5,
                ),
              ),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(type['icon'], size: 22, color: isSelected ? context.colors.accent : context.colors.textTertiary),
                  if (type['label'].isNotEmpty) ...[
                    const SizedBox(height: 6),
                    Text(
                      type['label'],
                      style: TextStyle(
                        fontSize: 13,
                        fontWeight: isSelected ? FontWeight.w500 : FontWeight.w400,
                        color: isSelected ? context.colors.accent : context.colors.textSecondary,
                      ),
                      overflow: TextOverflow.ellipsis,
                      maxLines: 1,
                    ),
                  ],
                ],
              ),
            ),
          ),
        );
      }).toList(),
    );
  }

  Widget _buildBalanceField() {
    return TextFormField(
      controller: _balanceController,
      style: context.styles.inputText,
      keyboardType: const TextInputType.numberWithOptions(decimal: true),
      inputFormatters: [
        FilteringTextInputFormatter.allow(RegExp(r'^\d+\.?\d{0,2}')),
      ],
      decoration: context.styles.input(
        hint: '0.00',
        prefixText: 'THB ',
      ),
      validator: (value) {
        if (value == null || value.trim().isEmpty) return null;
        final amount = double.tryParse(value);
        if (amount == null) return 'Please enter valid amount';
        return null;
      },
    );
  }

  Widget _buildBottomActions() {
    return Container(
      decoration: BoxDecoration(
        color: context.colors.cardBg,
        border: Border(top: BorderSide(color: context.colors.divider)),
      ),
      padding: const EdgeInsets.all(20),
      child: SafeArea(
        top: false,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                onPressed: _isLoading ? null : _handleSaveAccount,
                style: context.styles.primaryButton,
                child: _isLoading
                    ? const SizedBox(
                        height: 20, width: 20,
                        child: CircularProgressIndicator(strokeWidth: 2, valueColor: AlwaysStoppedAnimation<Color>(Colors.white)),
                      )
                    : Text(_isEditMode ? 'Save Changes' : 'Create Account'),
              ),
            ),
            const SizedBox(height: 12),
            SizedBox(
              width: double.infinity,
              child: OutlinedButton(
                onPressed: _isLoading ? null : () => Navigator.pop(context),
                style: context.styles.secondaryButton,
                child: const Text('Cancel'),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
