import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../domain/entities/account.dart';
import '../bloc/account_bloc.dart';

/// ═══════════════════════════════════════════════════════════════════════════
/// Account Create/Edit Screen - Form to create or edit account
/// ═══════════════════════════════════════════════════════════════════════════
class AccountCreateScreen extends StatefulWidget {
  final Account? account;
  
  const AccountCreateScreen({super.key, this.account});

  @override
  State<AccountCreateScreen> createState() => _AccountCreateScreenState();
}

class _AccountCreateScreenState extends State<AccountCreateScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _balanceController = TextEditingController();
  final _notesController = TextEditingController();

  String _selectedType = 'bank';
  bool _isLoading = false;
  bool _isEditMode = false;

  // Account type options
  final List<Map<String, dynamic>> _accountTypes = [
    {'value': 'bank', 'label': 'Bank', 'icon': Icons.account_balance, 'enabled': true},
    {'value': 'cash', 'label': 'Cash', 'icon': Icons.money, 'enabled': true},
    {'value': 'ewallet', 'label': 'Wallet', 'icon': Icons.wallet, 'enabled': true},
    {'value': 'other', 'label': '', 'icon': Icons.help_outline, 'enabled': false},
  ];

  @override
  void initState() {
    super.initState();
    _isEditMode = widget.account != null;
    
    // Populate fields if editing
    if (widget.account != null) {
      _nameController.text = widget.account!.name;
      _balanceController.text = widget.account!.balance.toStringAsFixed(2);
      _selectedType = widget.account!.type;
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _balanceController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Actions
  // ─────────────────────────────────────────────────────────────────────────

  /// Handle create or update account
  Future<void> _handleSaveAccount() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final balance = double.tryParse(_balanceController.text) ?? 0.0;
      final now = DateTime.now();

      if (_isEditMode) {
        // Update existing account
        final updatedAccount = widget.account!.copyWith(
          name: _nameController.text.trim(),
          type: _selectedType,
          balance: balance,
          updatedAt: now,
        );

        print('📝 Updating account: ${updatedAccount.name} (${updatedAccount.type}) - Balance: ${updatedAccount.balance}');

        if (mounted) {
          context.read<AccountBloc>().add(UpdateAccountRequested(updatedAccount));
        }
      } else {
        // Create new account
        final account = Account(
          id: '', // Will be generated by database
          name: _nameController.text.trim(),
          type: _selectedType,
          openingBalance: balance,
          balance: balance,
          currency: 'THB', // App supports only Thai Baht
          createdAt: now,
          updatedAt: now,
        );

        print('📝 Creating account: ${account.name} (${account.type}) - Balance: ${account.balance} ${account.currency}');

        if (mounted) {
          context.read<AccountBloc>().add(CreateAccountRequested(account));
        }
      }
      
      // Wait for the bloc to process the event
      await Future.delayed(const Duration(milliseconds: 800));
      
      // Return success
      if (mounted) {
        print('✅ Account save completed, navigating back');
        Navigator.pop(context, true);
      }
    } catch (e) {
      print('❌ Account save error: $e');
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to save account: $e'),
            backgroundColor: Colors.red[700],
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Build Methods
  // ─────────────────────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: _buildAppBar(),
      body: _buildBody(),
    );
  }

  /// Build app bar
  PreferredSizeWidget _buildAppBar() {
    return AppBar(
      backgroundColor: const Color(0xFF4D648D),
      elevation: 0,
      leading: IconButton(
        icon: const Icon(Icons.arrow_back, color: Colors.white),
        onPressed: () => Navigator.pop(context),
      ),
      title: Text(
        _isEditMode ? 'Edit Account' : 'Create Account',
        style: const TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.w600,
        ),
      ),
    );
  }

  /// Build body
  Widget _buildBody() {
    return Column(
      children: [
        Expanded(
          child: SingleChildScrollView(
            padding: const EdgeInsets.fromLTRB(20, 24, 20, 140),
            child: Form(
              key: _formKey,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Account name field
                  _buildSectionLabel('Account Name'),
                  const SizedBox(height: 8),
                  _buildNameField(),
                  const SizedBox(height: 24),

                  // Account type field
                  _buildSectionLabel('Account Type'),
                  const SizedBox(height: 12),
                  _buildTypeSelector(),
                  const SizedBox(height: 24),

                  // Current balance field
                  _buildSectionLabel('Current Balance'),
                  const SizedBox(height: 12),
                  _buildBalanceField(),
                  const SizedBox(height: 8),
                  Text(
                    'This reflects how much money is currently in this account.',
                    style: TextStyle(
                      fontSize: 12,
                      color: Colors.grey[500],
                    ),
                  ),
                  const SizedBox(height: 32),

                  // Optional settings section
                  _buildSectionLabel('Optional Settings'),
                  const SizedBox(height: 16),
                  _buildNotesField(),
                ],
              ),
            ),
          ),
        ),
        _buildBottomActions(),
      ],
    );
  }

  /// Build section label
  Widget _buildSectionLabel(String label) {
    return Text(
      label,
      style: TextStyle(
        fontSize: 14,
        color: Colors.grey[700],
      ),
    );
  }

  /// Build account name field
  Widget _buildNameField() {
    return TextFormField(
      controller: _nameController,
      decoration: InputDecoration(
        hintText: 'e.g. Main Bank, Cash, Wallet',
        hintStyle: TextStyle(color: Colors.grey[400]),
        filled: true,
        fillColor: Colors.white,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: Color(0xFFD4D4D4)),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: Color(0xFFD4D4D4)),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: Color(0xFF4D648D)),
        ),
        contentPadding: const EdgeInsets.all(12),
      ),
      validator: (value) {
        if (value == null || value.trim().isEmpty) {
          return 'Please enter account name';
        }
        return null;
      },
    );
  }

  /// Build account type selector
  Widget _buildTypeSelector() {
    return GridView.count(
      crossAxisCount: 2,
      shrinkWrap: true,
      physics: const NeverScrollableScrollPhysics(),
      crossAxisSpacing: 12,
      mainAxisSpacing: 12,
      childAspectRatio: 2.5,
      padding: EdgeInsets.zero,
      children: _accountTypes.map((type) {
        final isSelected = _selectedType == type['value'];
        final isEnabled = type['enabled'] as bool;
        
        return InkWell(
          onTap: isEnabled ? () => setState(() => _selectedType = type['value']) : null,
          borderRadius: BorderRadius.circular(8),
          child: Opacity(
            opacity: isEnabled ? 1.0 : 0.5,
            child: Container(
              padding: const EdgeInsets.all(0),
              decoration: BoxDecoration(
                color: isSelected ? const Color(0xFF4D648D).withValues(alpha: 0.05) : Colors.white,
                borderRadius: BorderRadius.circular(8),
                border: Border.all(
                  color: isSelected ? const Color(0xFF4D648D) : const Color(0xFFD4D4D4),
                  width: isSelected ? 2 : 1,
                ),
              ),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(
                    type['icon'],
                    size: 24,
                    color: isSelected ? const Color(0xFF4D648D) : Colors.grey[400],
                  ),
                  if (type['label'].isNotEmpty) ...[
                    const SizedBox(height: 8),
                    Text(
                      type['label'],
                      style: TextStyle(
                        fontSize: 14,
                        color: isSelected ? const Color(0xFF4D648D) : Colors.grey[600],
                      ),
                      overflow: TextOverflow.ellipsis,
                      maxLines: 1,
                    ),
                  ],
                ],
              ),
            ),
          ),
        );
      }).toList(),
    );
  }

  /// Build balance field
  Widget _buildBalanceField() {
    return TextFormField(
      controller: _balanceController,
      keyboardType: const TextInputType.numberWithOptions(decimal: true),
      inputFormatters: [
        FilteringTextInputFormatter.allow(RegExp(r'^\d+\.?\d{0,2}')),
      ],
      decoration: InputDecoration(
        hintText: '0.00',
        hintStyle: TextStyle(color: Colors.grey[400]),
        prefixIcon: Padding(
          padding: const EdgeInsets.only(left: 16, right: 8),
          child: Text(
            '฿',
            style: TextStyle(
              fontSize: 16,
              color: Colors.grey[600],
            ),
          ),
        ),
        prefixIconConstraints: const BoxConstraints(minWidth: 0, minHeight: 0),
        filled: true,
        fillColor: Colors.white,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: Color(0xFFD4D4D4)),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: Color(0xFFD4D4D4)),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: Color(0xFF4D648D)),
        ),
        contentPadding: const EdgeInsets.symmetric(
          horizontal: 16,
          vertical: 12,
        ),
      ),
      validator: (value) {
        if (value == null || value.trim().isEmpty) {
          return null; // Optional field
        }
        final amount = double.tryParse(value);
        if (amount == null) {
          return 'Please enter valid amount';
        }
        return null;
      },
    );
  }

  /// Build notes field
  Widget _buildNotesField() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Notes (Optional)',
          style: TextStyle(
            fontSize: 14,
            color: Colors.grey[700],
          ),
        ),
        const SizedBox(height: 8),
        TextFormField(
          controller: _notesController,
          maxLines: 3,
          decoration: InputDecoration(
            hintText: 'Add any additional details...',
            hintStyle: TextStyle(color: Colors.grey[400]),
            filled: true,
            fillColor: Colors.white,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: const BorderSide(color: Color(0xFFD4D4D4)),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: const BorderSide(color: Color(0xFFD4D4D4)),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: const BorderSide(color: Color(0xFF4D648D)),
            ),
            contentPadding: const EdgeInsets.all(12),
          ),
        ),
      ],
    );
  }

  /// Build bottom action buttons
  Widget _buildBottomActions() {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        border: Border(
          top: BorderSide(color: Colors.grey.shade200),
        ),
      ),
      padding: const EdgeInsets.all(20),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          // Save button
          SizedBox(
            width: double.infinity,
            child: ElevatedButton(
              onPressed: _isLoading ? null : _handleSaveAccount,
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF4D648D),
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8),
                ),
                elevation: 0,
                disabledBackgroundColor: Colors.grey[300],
              ),
              child: _isLoading
                  ? const SizedBox(
                      height: 20,
                      width: 20,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                      ),
                    )
                  : Text(
                      _isEditMode ? 'Save Changes' : 'Create Account',
                      style: const TextStyle(
                        fontSize: 16,
                      ),
                    ),
            ),
          ),
          const SizedBox(height: 12),
          // Cancel button
          SizedBox(
            width: double.infinity,
            child: OutlinedButton(
              onPressed: _isLoading ? null : () => Navigator.pop(context),
              style: OutlinedButton.styleFrom(
                foregroundColor: Colors.grey[600],
                padding: const EdgeInsets.symmetric(vertical: 16),
                side: BorderSide(color: Colors.grey.shade300),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8),
                ),
              ),
              child: const Text(
                'Cancel',
                style: TextStyle(
                  fontSize: 16,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
